import mongoose from 'mongoose';

const userSchema = new mongoose.Schema({
    displayName: { type: String, required: true },
    email: { type: String, unique: true, sparse: true },
    phone: { type: String, unique: true, sparse: true },
    password: { type: String },
    role: { type: String, default: 'folk_member' },
    centerId: { type: mongoose.Schema.Types.ObjectId, ref: 'Center' },
    batchId: { type: mongoose.Schema.Types.ObjectId, ref: 'Batch' },
    spiritualName: { type: String },
    initiatedBy: { type: String, default: 'HDG A.C. Bhaktivedanta Swami Prabhupada' },
    initiationDate: { type: Date },
    chantingRounds: { type: Number, default: 0 },
    vows: { type: mongoose.Schema.Types.Mixed },
    yearsInKC: { type: Number, default: 0 },
    legalName: { type: String },
    dateOfBirth: { type: Date },
    gender: { type: String },
    languages: [String],
    addressStreet: { type: String },
    addressCity: { type: String },
    addressState: { type: String },
    addressPincode: { type: String },
    bloodGroup: { type: String },
    qualification: { type: String },
    occupation: { type: String },
    organization: { type: String },
    designation: { type: String },
    industry: { type: String },
    incomeRange: { type: String },
    maritalStatus: { type: String },
    spouseName: { type: String },
    childrenCount: { type: Number, default: 0 },
    parentsNames: { type: mongoose.Schema.Types.Mixed },
    skills: [String],
    sevaAvailability: [String],
    canHostDevotees: { type: Boolean, default: false },
    spiritualGoals: { type: String },
    favoriteScripture: { type: String },
    lifeMission: { type: String },
    profileComplete: { type: Number, default: 0 },
    followingIds: [{ type: mongoose.Schema.Types.ObjectId, ref: 'User' }],
    followerIds: [{ type: mongoose.Schema.Types.ObjectId, ref: 'User' }],
    circleIds: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Circle' }],
    createdAt: { type: Date, default: Date.now }
});

const User = mongoose.model('User', userSchema);
export default User;
